"""
Neuron shape generation module.

Generates realistic neuron (soma) and nucleus shapes using Gaussian
process sampling on a sphere surface with geodesic covariance.
"""

import numpy as np
from typing import Optional, Tuple, List
from scipy.spatial import ConvexHull, Delaunay
from scipy.ndimage import binary_dilation

from ..config.params import NeuronParams, VolumeParams


def _ensure_nucleus_inside_soma(
    Vcell: np.ndarray,
    Vnuc: np.ndarray,
    margin: float = 0.1,
) -> np.ndarray:
    """
    Ensure all nucleus vertices are inside the actual soma surface.

    Uses a radial/directional check: for each nucleus vertex, finds the
    soma vertex in the most similar direction from center, and ensures
    the nucleus vertex is closer to center than that soma vertex.

    This handles the bumpy GP-sampled soma surface correctly, unlike
    a simple convex hull check.

    Args:
        Vcell: (N, 3) soma surface vertices.
        Vnuc: (N, 3) nucleus surface vertices.
        margin: Safety margin in micrometers (default 0.1 um).

    Returns:
        Adjusted Vnuc array with all vertices inside soma surface.
    """
    soma_center = np.mean(Vcell, axis=0)

    # Precompute soma directions and distances from center
    soma_dirs = Vcell - soma_center
    soma_dists = np.linalg.norm(soma_dirs, axis=1)
    soma_dists_safe = np.maximum(soma_dists, 1e-10)
    soma_dirs_normalized = soma_dirs / soma_dists_safe[:, np.newaxis]

    def get_max_allowed_dist(direction):
        """Get the maximum allowed distance from soma_center in given direction."""
        if np.linalg.norm(direction) < 1e-10:
            return 0.0
        dir_normalized = direction / np.linalg.norm(direction)
        dots = np.dot(soma_dirs_normalized, dir_normalized)
        closest_idx = np.argmax(dots)
        return soma_dists[closest_idx] - margin

    # Iteratively scale nucleus until all vertices are inside
    Vnuc_adjusted = Vnuc.copy()
    nuc_center = np.mean(Vnuc, axis=0)

    for iteration in range(10):  # Max 10 iterations
        # Check all vertices and find the worst violation
        max_ratio = 1.0  # ratio of nuc_dist / allowed_dist
        for i in range(len(Vnuc_adjusted)):
            nuc_dir = Vnuc_adjusted[i] - soma_center
            nuc_dist = np.linalg.norm(nuc_dir)
            if nuc_dist < 1e-6:
                continue

            allowed_dist = get_max_allowed_dist(nuc_dir)
            if allowed_dist > 0:
                ratio = nuc_dist / allowed_dist
                if ratio > max_ratio:
                    max_ratio = ratio

        # If no violations, we're done
        if max_ratio <= 1.0:
            break

        # Scale down the nucleus
        # Use a slightly larger scale factor to converge faster
        scale = 0.95 / max_ratio
        scale = max(scale, 0.8)  # Don't shrink too aggressively in one step

        # Scale relative to nucleus center
        Vnuc_adjusted = nuc_center + (Vnuc_adjusted - nuc_center) * scale

    return Vnuc_adjusted
from ..geometry.sphere_sampling import spiral_sample_sphere
from ..algorithms.gaussian_process import (
    sample_gp_sphere,
    teardrop_projection,
    compute_geodesic_covariance,
    ensure_psd,
)


def generate_neural_body(
    neur_params: Optional[NeuronParams] = None,
    vertices: Optional[np.ndarray] = None,
    faces: Optional[np.ndarray] = None,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Generate a neural soma and nucleus shape using GP sampling.

    The soma shape is generated by:
    1. Sampling points uniformly on a unit sphere
    2. Computing GP covariance based on geodesic distances
    3. Sampling radii from the GP
    4. Applying teardrop projection for pyramidal neurons
    5. Creating an elliptical nucleus inside

    Args:
        neur_params: Neuron parameters. Uses defaults if None.
        vertices: Optional pre-computed sphere vertices (N, 3).
        faces: Optional pre-computed triangulation (M, 3).

    Returns:
        Vcell: (N, 3) soma surface vertices in micrometers.
        Vnuc: (N, 3) nucleus surface vertices in micrometers.
        Tri: (M, 3) face connectivity (same for both).
        angles: (3,) rotation angles applied (degrees).
    """
    if neur_params is None:
        neur_params = NeuronParams()

    # GP power - sensitive parameter, don't change
    power = 1.0
    nuc_offset = 3.0  # Nucleus offset for shape generation

    # Get sphere sampling
    if vertices is None or faces is None:
        vertices, faces = spiral_sample_sphere(
            neur_params.n_samps, return_triangulation=True
        )

    n_points = len(vertices)

    # Compute teardrop projection for pyramidal neurons
    # Supported types:
    #   'pyramidal' / 'pyr' - teardrop shape for cortical pyramidal cells
    #   'spherical'         - spherical shape for granule cells, MSNs
    #   'stellate'          - highly spherical for cortical layer IV stellate cells
    #   'fusiform'          - elongated ellipsoid for spindle-shaped neurons
    if neur_params.neur_type in ('pyr', 'pyramidal'):
        V_tear = teardrop_projection(vertices, p=1)
        R_tear = np.linalg.norm(V_tear, axis=1)
    else:
        # Spherical base for 'spherical', 'fusiform', and other types
        V_tear = vertices.copy()
        R_tear = np.ones(n_points)

    # Sample from GP with geodesic covariance
    # The mean is zero, we add the teardrop radii after sampling
    x_base = sample_gp_sphere(
        vertices,
        l_scale=neur_params.l_scale,
        p_scale=neur_params.p_scale,
        power=power,
        mean=None,
    )
    x_base = np.abs(x_base)  # Take absolute value

    # Apply bounds to radii
    x_bnds = (
        neur_params.exts[0] * neur_params.avg_rad,
        neur_params.exts[1] * neur_params.avg_rad,
    )

    # Re-center and scale to target average radius
    x = x_base - np.mean(x_base) + neur_params.avg_rad * R_tear

    # Normalize to bounds
    x_min = min(np.min(x), x_bnds[0])
    x_max = max(np.max(x), x_bnds[1])
    x = (x_bnds[1] - x_bnds[0]) * (x - x_min) / (x_max - x_min) + x_bnds[0]

    # For pyramidal neurons, nucleus uses unit sphere (not teardrop)
    if neur_params.neur_type in ('pyr', 'pyramidal'):
        x2 = x_base - np.mean(x_base) + neur_params.avg_rad
        x2_min = min(np.min(x2), x_bnds[0])
        x2_max = max(np.max(x2), x_bnds[1])
        x2 = (x_bnds[1] - x_bnds[0]) * (x2 - x2_min) / (x2_max - x2_min) + x_bnds[0]
    else:
        x2 = x.copy()

    # Create elliptical shape with random eccentricity
    eccen_vec = np.ones(3) + neur_params.eccen * (
        np.random.rand(3) - np.array([0.5, 0.5, 0.0])
    )
    # Normalize to preserve volume
    eccen_vec = eccen_vec / (np.prod(eccen_vec) ** (1 / 3))

    # Create elliptical teardrop for soma
    if neur_params.neur_type in ('pyr', 'pyramidal'):
        V_ellip = V_tear * eccen_vec
    elif neur_params.neur_type == 'fusiform':
        # Fusiform: elongated along z-axis
        fusiform_eccen = eccen_vec * np.array([0.7, 0.7, 1.4])
        fusiform_eccen = fusiform_eccen / (np.prod(fusiform_eccen) ** (1 / 3))
        V_ellip = vertices * fusiform_eccen
    elif neur_params.neur_type == 'stellate':
        # Stellate: more spherical with reduced eccentricity (uniform radial dendrites)
        stellate_eccen = 1 + (eccen_vec - 1) * 0.3  # Reduce eccentricity to 30%
        stellate_eccen = stellate_eccen / (np.prod(stellate_eccen) ** (1 / 3))
        V_ellip = vertices * stellate_eccen
    else:
        # Spherical (default for 'spherical', 'granule', etc.)
        V_ellip = vertices * eccen_vec

    # Normalize elliptical shape
    V_ellip = V_ellip / np.sqrt(np.mean(np.sum(V_ellip ** 2, axis=1)))

    # Create soma surface by scaling with sampled radii
    Vcell = V_ellip * x[:, np.newaxis]
    Vcell = Vcell + np.array([0, 0, -nuc_offset])  # Shift down

    # Get soma surface extents
    Vnorms = np.linalg.norm(Vcell, axis=1)

    # Create nucleus shape
    # Flip z-component for nucleus
    V_nuc_base = vertices * np.array([1, 1, -1])
    Vnuc = V_nuc_base * x2[:, np.newaxis]

    # Get nucleus extents and apply shrinking/smoothing
    Vnorms2 = np.linalg.norm(Vnuc, axis=1)
    Vnorms2 = neur_params.nexts[1] * (
        neur_params.nexts[0] * (Vnorms2 - np.min(Vnorms2))
        + (1 - neur_params.nexts[0]) * np.max(Vnorms2)
    )

    # Ensure nucleus fits inside soma with minimum thickness
    Vnorms2 = Vnorms2 + np.min(Vnorms - Vnorms2) - neur_params.min_thic[0]

    # Apply eccentricity and shrinkage to nucleus
    # IMPORTANT: Must compute scale factor BEFORE applying eccen_vec
    # to match MATLAB: Vnuc = Vnuc * eccens * (Vnorms2 / norm(Vnuc))
    nuc_norms_before_eccen = np.linalg.norm(Vnuc, axis=1)
    Vnuc = Vnuc * eccen_vec * (Vnorms2 / nuc_norms_before_eccen)[:, np.newaxis]

    # Random lateral shift for nucleus
    lat_ang = np.random.rand() * 2 * np.pi
    lat_shift_mag = (1 - np.abs(np.random.rand() - np.random.rand())) * neur_params.min_thic[1]
    lat_shift = lat_shift_mag * np.array([np.sin(lat_ang), np.cos(lat_ang), 0])

    # Shift soma and nucleus back up
    Vcell = Vcell + np.array([0, 0, nuc_offset])
    Vnuc = Vnuc + np.array([lat_shift[0], lat_shift[1], nuc_offset])

    # Optional: scale nucleus to target radius
    if neur_params.nuc_rad is not None and len(neur_params.nuc_rad) > 0:
        try:
            hull = ConvexHull(Vnuc)
            current_vol = hull.volume
            target_vol = (4 / 3) * np.pi * (neur_params.nuc_rad[0] ** 3)

            if len(neur_params.nuc_rad) > 1:
                scale = (target_vol / current_vol) ** (1 / 3 / neur_params.nuc_rad[1])
            else:
                scale = (target_vol / current_vol) ** (1 / 3)

            Vnuc = Vnuc * scale
        except Exception:
            pass  # Skip scaling if convex hull fails

    # Apply random rotation
    max_ang = neur_params.max_ang
    angles = -np.abs(max_ang) + 2 * np.abs(max_ang) * np.random.rand(3)

    # Rotation matrices (using degrees)
    Rx = _rotation_matrix_x(angles[0])
    Ry = _rotation_matrix_y(angles[1])
    Rz = _rotation_matrix_z(angles[2])

    # Apply rotations
    R = Rx @ Ry @ Rz
    Vcell = Vcell @ R
    Vnuc = Vnuc @ R

    return Vcell, Vnuc, faces, angles


def _rotation_matrix_x(angle_deg: float) -> np.ndarray:
    """Create rotation matrix around x-axis."""
    c = np.cos(np.radians(angle_deg))
    s = np.sin(np.radians(angle_deg))
    return np.array([
        [1, 0, 0],
        [0, c, -s],
        [0, s, c]
    ])


def _rotation_matrix_y(angle_deg: float) -> np.ndarray:
    """Create rotation matrix around y-axis."""
    c = np.cos(np.radians(angle_deg))
    s = np.sin(np.radians(angle_deg))
    return np.array([
        [c, 0, s],
        [0, 1, 0],
        [-s, 0, c]
    ])


def _rotation_matrix_z(angle_deg: float) -> np.ndarray:
    """Create rotation matrix around z-axis."""
    c = np.cos(np.radians(angle_deg))
    s = np.sin(np.radians(angle_deg))
    return np.array([
        [c, -s, 0],
        [s, c, 0],
        [0, 0, 1]
    ])


def generate_multiple_neurons(
    n_neurons: int,
    neur_params: Optional[NeuronParams] = None,
    positions: Optional[np.ndarray] = None,
) -> Tuple[list, list, np.ndarray]:
    """
    Generate multiple neuron shapes.

    Args:
        n_neurons: Number of neurons to generate.
        neur_params: Neuron parameters (shared for all neurons).
        positions: (n_neurons, 3) array of neuron center positions.
                  If None, neurons are placed at origin.

    Returns:
        neurons: List of (Vcell, Vnuc, faces) tuples.
        angles: List of rotation angle arrays.
        positions: (n_neurons, 3) positions used.
    """
    if neur_params is None:
        neur_params = NeuronParams()

    if positions is None:
        positions = np.zeros((n_neurons, 3))

    # Pre-compute sphere sampling (reuse for all neurons)
    vertices, faces = spiral_sample_sphere(
        neur_params.n_samps, return_triangulation=True
    )

    neurons = []
    all_angles = []

    for i in range(n_neurons):
        Vcell, Vnuc, _, angles = generate_neural_body(
            neur_params, vertices=vertices, faces=faces
        )

        # Translate to position
        Vcell = Vcell + positions[i]
        Vnuc = Vnuc + positions[i]

        neurons.append((Vcell, Vnuc, faces))
        all_angles.append(angles)

    return neurons, all_angles, positions


def sample_dense_neurons(
    vol_params: Optional[VolumeParams] = None,
    neur_params: Optional[NeuronParams] = None,
    vessel_mask: Optional[np.ndarray] = None,
    verbose: int = 1,
) -> Tuple[List[tuple], List[np.ndarray], np.ndarray]:
    """
    Sample neuron shapes and positions in a 3D volume with vessel avoidance.

    Implements a Poisson disk-like spatial exclusion sampling algorithm:
    1. Creates a 3D grid of candidate positions at vres resolution
    2. Dilates vessel mask by min_dist/2 to create buffer zone
    3. Iteratively samples random valid positions
    4. Excludes nearby positions using dual-distance approach (eta=1.1)
    5. Terminates when target N_neur reached or no valid positions remain

    Based on MATLAB sampleDenseNeurons.m algorithm.

    Args:
        vol_params: Volume parameters containing vol_sz, min_dist, vres, N_neur.
                   Uses defaults if None.
        neur_params: Neuron parameters for shape generation.
                    Uses defaults if None.
        vessel_mask: Optional 3D binary mask (uint8) of vessel locations.
                    Shape should be (vol_sz * vres). If None, no vessel
                    avoidance is performed.
        verbose: Verbosity level (0=silent, 1=progress, 2=detailed).

    Returns:
        neurons: List of (Vcell, Vnuc, faces) tuples for each neuron.
                 Vcell and Vnuc are already translated to final positions.
        angles: List of rotation angle arrays (3,) for each neuron.
        positions: (N, 3) array of neuron center positions in micrometers.

    Example:
        >>> from calcia.config.params import VolumeParams, NeuronParams
        >>> vol_params = VolumeParams(vol_sz=(100, 100, 50), N_neur=20)
        >>> neur_params = NeuronParams()
        >>> neurons, angles, positions = sample_dense_neurons(vol_params, neur_params)
        >>> print(f"Placed {len(neurons)} neurons")

    Note:
        The actual number of neurons returned may be less than vol_params.N_neur
        if the volume becomes saturated before reaching the target.
    """
    # Parse and validate parameters
    if vol_params is None:
        vol_params = VolumeParams()
    if neur_params is None:
        neur_params = NeuronParams()

    vol_sz = np.array(vol_params.vol_sz, dtype=np.float32)
    vres = vol_params.vres
    min_dist = vol_params.min_dist
    n_neur_target = vol_params.N_neur
    eta = 1.1  # Dual-distance factor from MATLAB

    # Create 3D coordinate grid
    grid_shape = tuple(int(s * vres) for s in vol_sz)
    x_coords = np.linspace(0, vol_sz[0], grid_shape[0], dtype=np.float32)
    y_coords = np.linspace(0, vol_sz[1], grid_shape[1], dtype=np.float32)
    z_coords = np.linspace(0, vol_sz[2], grid_shape[2], dtype=np.float32)

    # Prepare vessel exclusion zone
    if vessel_mask is not None:
        # Validate vessel mask shape
        if vessel_mask.shape != grid_shape:
            raise ValueError(
                f"vessel_mask shape {vessel_mask.shape} does not match "
                f"expected shape {grid_shape} (vol_sz * vres)"
            )

        # Create spherical structuring element for dilation
        dilation_radius = int(np.ceil(min_dist / 2 * vres))

        # Create 3D spherical kernel
        x, y, z = np.ogrid[
            -dilation_radius : dilation_radius + 1,
            -dilation_radius : dilation_radius + 1,
            -dilation_radius : dilation_radius + 1,
        ]
        kernel = (x**2 + y**2 + z**2) <= (dilation_radius**2)

        # Dilate vessel mask
        vessel_dilated = binary_dilation(vessel_mask > 0, structure=kernel)
    else:
        vessel_dilated = np.zeros(grid_shape, dtype=bool)

    # Initialize valid position masks
    # idx_good: positions available for sampling (uses eta * min_dist exclusion)
    # idx_bad: positions excluded by strict min_dist (for fallback sampling)
    idx_good = ~vessel_dilated.copy()
    idx_bad = idx_good.copy()

    n_available = np.sum(idx_good)
    if verbose >= 1:
        print(f"Target: {n_neur_target} neurons, Min distance: {min_dist:.1f} um")
        print(f"Available placement locations: {n_available}")

    if n_available == 0:
        if verbose >= 1:
            print("Warning: No valid placement locations available.")
        return [], [], np.array([]).reshape(0, 3)

    # Pre-compute sphere vertices and faces (reused for all neurons)
    vertices, faces = spiral_sample_sphere(
        neur_params.n_samps, return_triangulation=True
    )

    # Main sampling loop
    neurons = []
    angles_list = []
    positions_list = []

    # O(N) sampling state: keep RUNNING valid counts (so we never re-sum the
    # whole grid each iteration) and a local exclusion-box radius (so we never
    # build a whole-volume distance field just to exclude a min_dist sphere).
    # These turn the loop from O(N * V) into ~O(N).
    n_good = int(np.sum(idx_good))
    n_bad = int(np.sum(idx_bad))
    gs0, gs1, gs2 = grid_shape
    excl_r = int(np.ceil(eta * min_dist * vres))  # box half-size >= eta*min_dist
    reject_cap = 64

    for k in range(n_neur_target):
        # Termination via running counts (no whole-grid re-sum).
        if n_good == 0 and n_bad == 0:
            if verbose >= 1:
                print(f"No valid positions remaining. Stopping at {k} neurons.")
            break

        # Generate neuron shape
        Vcell, Vnuc, _, rot_angles = generate_neural_body(
            neur_params, vertices=vertices, faces=faces
        )

        # Sample a valid position by REJECTION: pick a uniform-random voxel and
        # retry if it is not valid. This is the SAME distribution as scanning the
        # whole mask (uniform over valid voxels) but O(1) amortized instead of an
        # O(V) flatnonzero every iteration. Only when the mask is nearly
        # saturated (rejection keeps failing) do we fall back to a single scan.
        mask = idx_good if n_good > 0 else idx_bad
        ix = iy = iz = None
        for _ in range(reject_cap):
            cx = np.random.randint(gs0)
            cy = np.random.randint(gs1)
            cz = np.random.randint(gs2)
            if mask[cx, cy, cz]:
                ix, iy, iz = cx, cy, cz
                break
        if ix is None:  # nearly saturated -> exact scan (rare)
            valid_indices = np.flatnonzero(mask.ravel())
            if len(valid_indices) == 0:
                if verbose >= 1:
                    print(f"No valid positions remaining. Stopping at {k} neurons.")
                break
            ix, iy, iz = np.unravel_index(
                valid_indices[np.random.randint(len(valid_indices))], grid_shape)

        new_pos = np.array([x_coords[ix], y_coords[iy], z_coords[iz]], dtype=np.float32)

        # Special case: center single neuron
        if n_neur_target == 1:
            new_pos = np.round(vol_sz / 2).astype(np.float32)

        positions_list.append(new_pos)

        # Translate neuron to position
        Vcell_translated = Vcell + new_pos
        Vnuc_translated = Vnuc + new_pos

        neurons.append((Vcell_translated, Vnuc_translated, faces))
        angles_list.append(rot_angles)

        # LOCAL exclusion: only touch the box that can possibly contain excluded
        # voxels (radius eta*min_dist), not the whole grid. Identical result to
        # the whole-volume masking (voxels outside are > min_dist, never
        # excluded) at O(min_dist^3) instead of O(V). The running valid counts
        # are updated by the box's before/after delta.
        x0, x1 = max(0, ix - excl_r), min(gs0, ix + excl_r + 1)
        y0, y1 = max(0, iy - excl_r), min(gs1, iy + excl_r + 1)
        z0, z1 = max(0, iz - excl_r), min(gs2, iz + excl_r + 1)
        lx = np.arange(x0, x1, dtype=np.float32) - ix
        ly = np.arange(y0, y1, dtype=np.float32) - iy
        lz = np.arange(z0, z1, dtype=np.float32) - iz
        dist_um = np.sqrt(lx[:, None, None]**2 + ly[None, :, None]**2
                          + lz[None, None, :]**2) / vres
        gb = idx_good[x0:x1, y0:y1, z0:z1]
        bb = idx_bad[x0:x1, y0:y1, z0:z1]
        g_before = int(gb.sum())
        b_before = int(bb.sum())
        gb[dist_um <= eta * min_dist] = False
        bb[dist_um <= min_dist] = False
        gb &= bb  # idx_good subset of idx_bad (only changes inside this box)
        n_good += int(gb.sum()) - g_before
        n_bad += int(bb.sum()) - b_before

        if verbose >= 2:
            print(f"Placed neuron {k + 1}/{n_neur_target} at ({new_pos[0]:.1f}, {new_pos[1]:.1f}, {new_pos[2]:.1f})")

    # Convert to arrays
    if positions_list:
        positions = np.array(positions_list, dtype=np.float32)
    else:
        positions = np.array([]).reshape(0, 3)

    if verbose >= 1:
        print(f"Neuron sampling complete: {len(neurons)} neurons placed.")

    return neurons, angles_list, positions


def compute_neuron_statistics(
    Vcell: np.ndarray,
    Vnuc: Optional[np.ndarray] = None,
) -> dict:
    """
    Compute statistics of a neuron shape.

    Args:
        Vcell: (N, 3) soma surface vertices.
        Vnuc: (N, 3) nucleus surface vertices (optional).

    Returns:
        Dictionary with statistics:
        - avg_radius: Average radius of soma
        - min_radius: Minimum radius
        - max_radius: Maximum radius
        - volume: Approximate volume (from convex hull)
        - surface_area: Approximate surface area
        - sphericity: How spherical the shape is (1 = perfect sphere)
    """
    stats = {}

    # Soma statistics
    radii = np.linalg.norm(Vcell, axis=1)
    stats['avg_radius'] = np.mean(radii)
    stats['min_radius'] = np.min(radii)
    stats['max_radius'] = np.max(radii)

    try:
        hull = ConvexHull(Vcell)
        stats['volume'] = hull.volume
        stats['surface_area'] = hull.area

        # Sphericity: ratio of surface area of equivalent sphere to actual
        equiv_radius = (3 * hull.volume / (4 * np.pi)) ** (1 / 3)
        equiv_area = 4 * np.pi * equiv_radius ** 2
        stats['sphericity'] = equiv_area / hull.area
    except Exception:
        stats['volume'] = None
        stats['surface_area'] = None
        stats['sphericity'] = None

    # Nucleus statistics
    if Vnuc is not None:
        nuc_radii = np.linalg.norm(Vnuc, axis=1)
        stats['nuc_avg_radius'] = np.mean(nuc_radii)

        try:
            nuc_hull = ConvexHull(Vnuc)
            stats['nuc_volume'] = nuc_hull.volume
        except Exception:
            stats['nuc_volume'] = None

    return stats
