"""
Inline every JSON/binary payload into one script, so the page needs no server.

WHY
    The page is already pure frontend -- there is no backend, and nothing runs
    at request time. But it reads its data with `fetch()`, and browsers refuse
    cross-origin `fetch` on `file://`. So opening index.html by double-clicking
    it fails, and a local preview needs *some* static file server.

    That is a loading detail, not an architecture. Writing the same payloads
    into a plain `<script>` removes it: script tags have no such restriction, so
    the folder opens straight off disk with nothing running at all.

    Media is unaffected -- <video> and <img> load fine from file://.

WHAT IT WRITES
    site/assets/data.js, defining window.CALCIA_DATA = {
        manifest, growth, gt, traces,     // parsed objects
        growthBin                         // base64 of growth.bin
    }

    app.js prefers this when present and falls back to fetch() when it is not,
    so a real deployment can still serve the files separately and let the
    browser cache them independently.

Run:
    conda run -n calcia python web/bundle_data.py
"""

import argparse
import base64
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_ASSETS = os.path.join(HERE, "site", "assets")

JSON_PARTS = [
    ("manifest", "manifest.json"),
    ("growth", os.path.join("growth", "growth.json")),
    ("gt", os.path.join("data", "gt.json")),
    ("traces", os.path.join("data", "traces.json")),
]
BIN_PARTS = [("growthBin", os.path.join("growth", "growth.bin"))]


def parse_args():
    p = argparse.ArgumentParser(
        description="Inline the site's data payloads into assets/data.js.")
    p.add_argument("--assets", default=DEFAULT_ASSETS,
                   help="Asset directory written by the other build scripts.")
    return p.parse_args()


def main():
    args = parse_args()
    root = os.path.abspath(args.assets)
    payload = {}

    print("=" * 68)
    print(f"Inlining data -> {os.path.join(root, 'data.js')}")
    print("=" * 68)

    for key, rel in JSON_PARTS:
        path = os.path.join(root, rel)
        if not os.path.exists(path):
            print(f"  {key:12s} missing ({rel}) -- skipped")
            continue
        with open(path, "r", encoding="utf-8") as fh:
            payload[key] = json.load(fh)
        print(f"  {key:12s} {os.path.getsize(path) / 1024.0:8.1f} KB")

    for key, rel in BIN_PARTS:
        path = os.path.join(root, rel)
        if not os.path.exists(path):
            print(f"  {key:12s} missing ({rel}) -- skipped")
            continue
        with open(path, "rb") as fh:
            raw = fh.read()
        payload[key] = base64.b64encode(raw).decode("ascii")
        print(f"  {key:12s} {len(raw) / 1024.0:8.1f} KB -> "
              f"{len(payload[key]) / 1024.0:8.1f} KB base64")

    out = os.path.join(root, "data.js")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("/* Generated by web/bundle_data.py -- do not edit.\n"
                 "   Lets the page run straight off the filesystem, with no\n"
                 "   server of any kind. app.js falls back to fetch() when this\n"
                 "   file is absent. */\n")
        fh.write("window.CALCIA_DATA = ")
        json.dump(payload, fh, separators=(",", ":"))
        fh.write(";\n")
    print("-" * 68)
    print(f"  data.js      {os.path.getsize(out) / 1024.0:8.1f} KB")
    print(f"Output: {out}")


if __name__ == "__main__":
    main()
